name: Build and Deploy Book

on:
  push:
    branches:
      - main  # o la rama que estés usando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc pandoc-citeproc
        Rscript -e 'install.packages(c("bookdown", "rmarkdown"))'

    - name: Build the book
      run: |
        Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

    - name: Clean up gh-pages branch
      run: |
        git fetch --prune --unshallow
        git checkout gh-pages
        git reset --hard origin/gh-pages
        git clean -dfx

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAT }}
        publish_dir: ./_book
        publish_branch: gh-pages
        keep_files: true
